# Day 6

https://adventofcode.com/2021/day/6

Part one can be completed by modelling each lanternfish individually, but the numbers get too large to fit in memory for part 2. Instead, model the number of lanternfish in each timer state, so that we only have to keep track of 9 numbers. One step in the simulation can then be simulated either using np.roll or (better) a transition matrix. 

In [1]:
import numpy as np

In [2]:
test_fish = np.array([3,4,3,1,2], dtype = np.int)

with open("input_06.txt", "r") as f:
    real_fish = f.read()
    
real_fish = np.array(real_fish.split(","), dtype = "int")

In [3]:
def sim_fish_slow(fish, n_days):
    """Simulate each fish individually."""
    for t in range(n_days):
        n_new_fish = len(fish[fish == 0])
        new_fish = np.ones(n_new_fish, dtype = np.int) * 9
        fish[fish == 0] = 7
        fish = np.concatenate((fish, new_fish))
        fish = fish - 1
    return fish
    
print(sim_fish_slow(test_fish, 18))
print(len(sim_fish_slow(test_fish, 80)))
print('')
print(len(sim_fish_slow(real_fish, 80)))

[6 0 6 4 5 6 0 1 1 2 6 0 1 1 1 2 2 3 3 4 6 7 8 8 8 8]
5934

394994


In [4]:
def timers(fish):
    return np.array([len(fish[fish == i]) for i in range(9)], dtype = "int64")

test_timers = timers(test_fish)
real_timers = timers(real_fish)

def sim_fish_loop(timers, n_days):
    """Simulate the number of fish at each timer using a loop."""
    for t in range(n_days):
        timers = np.roll(timers, -1)
        timers[6] = timers[6] + timers[8]
    
    return timers

print(sim_fish_loop(test_timers, 18))
print(sum(sim_fish_loop(test_timers, 80)))
print('')
print(sim_fish_loop(real_timers, 80))
print(sum(sim_fish_loop(real_timers, 80)))
print('')
print(sum(sim_fish_loop(test_timers, 256)))
print('')
print(sum(sim_fish_loop(real_timers, 256)))

[3 5 3 2 2 1 5 1 4]
5934

[14243 62094 24231 55542 48422 39452 83859 15512 51639]
394994

26984457539

1765974267455


In [5]:
from numpy.linalg import matrix_power

transition_matrix = np.array(
      [[0., 0., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype = "int64")


def sim_fish(timers, n_days):
    """Simulate the number of fish at each timer using powers of a transition matrix."""
    M = matrix_power(transition_matrix, n_days)
    return np.matmul(timers, M)

print(sim_fish(test_timers, 18))
print(sum(sim_fish(test_timers, 80)))
print('')
print(sim_fish(real_timers, 80))
print(sum(sim_fish(real_timers, 80)))
print('')
print(sum(sim_fish(test_timers, 256)))
print('')
print(sum(sim_fish(real_timers, 256)))

[3 5 3 2 2 1 5 1 4]
5934

[14243 62094 24231 55542 48422 39452 83859 15512 51639]
394994

26984457539

1765974267455
