# Day 5

https://adventofcode.com/2021/day/5

Create the ocean floor as a numpy array of zeros, then draw lines by adding one to each cell on the line. The number of intersections is then the number of cells with a value > 1.

In [1]:
import numpy as np

In [3]:
with open("test_input_05.txt", "r") as f:
    test_input = f.readlines()
    
with open("input_05.txt", "r") as f:
    real_input = f.readlines()
    

In [4]:
def brange(a, b):
    """Given a and b, return a tuple of all numbers x such that x >= min(a, b) and x <= max(a, b)"""
    if (a < b):
        return tuple(range(a, b + 1))
    elif (a > b):
        return tuple(range(a, b - 1, -1))
    else:
        return tuple([a])

def str_to_tuple(s):
    return tuple([int(n) for n in s.split(",")])

def line_ends_to_ranges(le):
    return tuple([brange(le["start"][i], le["end"][i]) for i in [1, 0]])
    
def line_ranges(test_input):
    pairs = [x.replace("\n", "").split(" -> ") for x in test_input]

    line_ends = [{"start": str_to_tuple(p[0]), "end": str_to_tuple(p[1])} for p in pairs]
    
    return [line_ends_to_ranges(le) for le in line_ends]

In [5]:
def max_extent(lr):
    """For a list of line ranges on a square map starting at (0, 0), return the width (== height) of the map"""
    m = 0
    for l in lr:
        for i in l:
            m = max(m, max(i))

    return m + 1

def draw_lines(line_ranges, diag = True):
    max_ext = max_extent(line_ranges)
    area = np.zeros((max_ext, max_ext))

    for lr in line_ranges:
        
        # if diagonal:
        if min(len(lr[0]), len(lr[1])) > 1:
            if diag:
                # do point-by-point
                points = zip(lr[0], lr[1])
                for p in points:
                    area[p] = area[p] + 1
        else: 
            area[lr] = area[lr] + 1
    
    return area

test_area_1 = draw_lines(line_ranges(test_input), diag = False)

print(test_area_1)
print(np.sum(test_area_1 > 1))
print('')

test_area_2 = draw_lines(line_ranges(test_input))
        
print(test_area_2)
print(np.sum(test_area_2 > 1))

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 1. 2. 1. 1. 1. 2. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 1. 1. 1. 0. 0. 0. 0.]]
5

[[1. 0. 1. 0. 0. 0. 0. 1. 1. 0.]
 [0. 1. 1. 1. 0. 0. 0. 2. 0. 0.]
 [0. 0. 2. 0. 1. 0. 1. 1. 1. 0.]
 [0. 0. 0. 1. 0. 2. 0. 2. 0. 0.]
 [0. 1. 1. 2. 3. 1. 3. 2. 1. 1.]
 [0. 0. 0. 1. 0. 2. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [2. 2. 2. 1. 1. 1. 0. 0. 0. 0.]]
12


In [6]:
area_1 = draw_lines(line_ranges(real_input), diag = False)

print(np.sum(area_1 > 1))
print('')
        
area_2 = draw_lines(line_ranges(real_input))

print(np.sum(area_2 > 1))

7644

18627
